### ISSUE TITLE
Switch to OAuth2

### ISSUE THREAD

**Issue by AnSq** [AnSq/IRCR_Info_Bot#5]
https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

> **Deprecation of cookie authentication for API consumers**
> 
> Use of the API when authenticated via cookies is deprecated and slated for removal. All API clients MUST convert to authenticating to the reddit API via OAuth 2 by **August 3, 2015**. After that date, reddit.com will begin heavily throttling and/or blocking API access that is not authenticated with an OAuth 2 access token*.

**Comment by AnSq** [comment]
Oh boy. It looks like I may need to combine the CommentScanner into the main thread, because it seems like PRAW with OAuth2 doesn't like using the same credentials in multiple threads. In fact, I even tried giving it different token files for each thread. In both cases I was getting a lot of `AssertionError`s like the following:

```
--------------------------------
*** ERROR: AssertionError: 
Traceback (most recent call last):
  File "IRCR_Info_Bot.py", line 699, in main
    scanSub(r, oauth, db, pg, testmode, mod_list)
  File "IRCR_Info_Bot.py", line 662, in scanSub
    posts = subreddit.get_new(limit=config.MAXPOSTS)
  File "<string>", line 2, in _sorted
  File "/home/ansq/Programs/IRCR_Info_Bot/env/lib/python2.7/site-packages/praw/decorators.py", line 247, in wrap
    assert not obj._use_oauth  # pylint: disable=W0212
AssertionError
--------------------------------
```

They came from all over my code, whenever it does a request through PRAW, but it's always raised in the same place, line 247 of decorators.py.

Actually it's probably better if they're the same thread anyway.

**Comment by AnSq** [comment]
Done by 49c052c95770905ea829c905ed51c1bdc5f4e54b...339ec091e17c0c1e8525e4a60656431155709db7.
